### ISSUE TITLE
Use meseeksdev for backporting

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#21070]
cc @jreback @jorisvandenbossche OK by you? Enable at https://github.com/apps/meeseeksdev/installations/new

I think @Carreau whitelisted the pandas org.

**Comment by jorisvandenbossche** [comment]
Just to understand the workflow here that would be used: Meeseeks will open a new PR for each PR that we tag for the bugfix release? (in constrast with the bulk cherry-picking that we now did more manually)

That gives some more traffic on github .. but on the other hand is also more transparent.

Anyhow, it's good to look at way to automate this more!

**Comment by Carreau** [comment]
So far it is based on milestone.
You edit your milestone description with commands to be executed on merge. 

For example IPython [5.7 milestone](https://github.com/ipython/ipython/milestone/52) contains:

```
on-merge: backport to 5.x
on-merge: backport to 6.x
```

So for example when https://github.com/ipython/ipython/pull/11043 was merged in master, the PR https://github.com/ipython/ipython/pull/11046 was automatically open.

If the bot can't cherry pick, it complains on the PR and tag it with "Still needs manual backport". for example :  https://github.com/ipython/ipython/pull/10707#issuecomment-317699092

You could of course add 

```
on-merge: say "Oweeeee"
```

Or any other command you like the bot understand. (tag, untag, say, ... )

You can also mention the bot and ask it to do things. _If_ you have commit right  on the repo (and the bot is enabled), the bot will respond. 

It push the backported branch on the same repository, because of some GitHub limitation as you can't make cross-repo PRs with integrations tokens. I have plan to fix that by creating a machine-account, and juggling with tokens, but so far haven't found the time to do it. 

Does that clarify things ?

**Comment by Carreau** [comment]
> It push the backported branch on the same repository, because of some GitHub limitation as you can't make cross-repo PRs with integrations tokens. I have plan to fix that by creating a machine-account, and juggling with tokens, but so far haven't found the time to do it.

I've now implemented (in beta) the ability to backport without requiring push permissions. See https://github.com/MeeseeksBox/MeeseeksDev/issues/28

I'll switch the default mechanism after some testing, and then remove the request for push access.

**Comment by jorisvandenbossche** [comment]
@Carreau thanks for the explanation! 

An additional question: it is also possible to have a command to say to the bot to still backport a PR once it is already merged? (eg in case you forgot to label it or only decide afterwards to still target it for that release, or now in our case because the bot was not yet enabled)

**Comment by TomAugspurger** [comment]
Should be `@MeeseeksDev backport to 0.23.x`.

**Comment by jorisvandenbossche** [comment]
Ideally I would like to have something that does backports in batches to avoid many PRs, but if this improves the workflow, let's go for it :)

**Comment by TomAugspurger** [comment]
I think I can manually backport this first batch, and then we'll start
using the bot for new ones.

**Comment by Carreau** [comment]
> Ideally I would like to have something that does backports in batches to avoid many PRs, but if this improves the workflow, let's go for it :)

If you want to have something that avoids PRs and push directly to stables branches it is feasible. We just need to modify the command to directly push. Which should not be too hard.

**Comment by TomAugspurger** [comment]
@MeeseeksDev Hello

**Comment by Carreau** [comment]
Hum... it may be case sensitive. Try lowercase ?

**Comment by jorisvandenbossche** [comment]
@meeseeksdev hello

**Comment by TomAugspurger** [comment]
FWIW, I *think* I requested permission for pandas-dev/pandas a couple days ago. Not sure if it went through.

**Comment by Carreau** [comment]
Hum, it did not receive any events from GitHub. Is it correctly activated ? I restarted the bot just in case.

**Comment by TomAugspurger** [comment]
Seems like it's still staging.

![screen shot 2018-06-12 at 9 14 49 am](https://user-images.githubusercontent.com/1312546/41295811-147b801c-6e21-11e8-9bed-fff446eeff5f.png)

**Comment by Carreau** [comment]
Hum, that's not from my end, I should not have to validate any of these.

**Comment by Carreau** [comment]
An admin of the org maybe ?

**Comment by TomAugspurger** [comment]
@MeeseeksDev Hello

**Comment by mroeschke** [comment]
Looks like we've enabled this. Closing
