### ISSUE TITLE
Cloning fork on Windows fails due to asv_bench/asv.conf.json

### ISSUE THREAD

**Issue by Michael-E-Rose** [pandas-dev/pandas#22648]
I just forked the pandas-dev/pandas repo and tried to clone it on my Windows [Version 6.1.7601] box.

```
Z:\software>git clone https://github.com/Michael-E-Rose/pandas.git
Cloning into 'pandas'...
remote: Counting objects: 152309, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 152309 (delta 6), reused 0 (delta 0), pack-reused 152301
Receiving objects: 100% (152309/152309), 122.89 MiB | 1.68 MiB/s, done.
Resolving deltas: 100% (125964/125964), done.
error: unable to create file asv_bench/asv.conf.json: No such file or directory
fatal: cannot create directory at 'asv_bench': No such file or directory
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```
First of all, upon (seeming) completion, the network drive Z disconnects.  Something along the process triggers that disconnect. After redownload, I tried `git status`, which results in a long list of green files marked deleted.  `git checkout -f HEAD` results in 

Z:\software\pandas>git checkout -f HEAD
fatal: Unable to create 'Z:/software/pandas/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.

Upon deletion of that lock file:

```
Z:\software\pandas>git checkout -f HEAD
error: unable to create file asv_bench/asv.conf.json: No such file or directory
fatal: cannot create directory at 'asv_bench/benchmarks': No such file or directory

```

**Comment by TomAugspurger** [comment]
That's strange. What version of git? If you remove the `pandas` folder git created and re-clone are things still broken?

**Comment by Michael-E-Rose** [comment]
My Git version is 2.18 and yes, I tried it multiple times. I read that sometimes Windows has troubles with non-ASCII characters and trailing blanks in file names or folder names. But then other Windows users would have the issue as well?!

**Comment by TomAugspurger** [comment]
Yes, we have windows developers and we test on windows. I'm not sure what
would be causing this.

**Comment by Michael-E-Rose** [comment]
Any ideas what I should look for? Might it be related to Windows, to Git or to that file?

**Comment by TomAugspurger** [comment]
No idea, sorry :/

**Comment by h-vetinari** [comment]
Not sure if any help, but I had some problems with git after upgrading my MSVC 2017 Community from 15.4 to 15.8.2. The errors were arcane, but in any case, I then found that this had been fixed in the git 2.19rc, which can be downloaded and installed from https://github.com/git-for-windows/git/releases (but 2.19 should hit very soon anyway, already slightly overdue: https://tinyurl.com/gitCal).

**Comment by Michael-E-Rose** [comment]
Alright thank you!   I will wait for 2.19 and report back.

**Comment by Michael-E-Rose** [comment]
Have upgraded to git 2.19 but the issue is still there.  This time I used GitHub for Windows:
```
error: unable to create file asv_bench/asv.conf.json: No such file or directory
fatal: cannot create directory at 'asv_bench': No such file or directory
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

**Comment by Liorin** [comment]
Michael - just to be sure: can you clone any other github repo on this machine?
Did you clone the pandas repo before? One thing you can try is to remove this file in your own fork and try cloning without it. 
I cloned your fork on my Ubuntu and did not have any problems.

**Comment by Michael-E-Rose** [comment]
I have investigated the issue with the IT department. We were able to clone the repo on a non-network drive. We were also able to put the problematic file on the network drive. So it seems to be the particular combination network drive+git that causes the error.
Meanwhile, I think, we can close this issue. It's not pandas fault.
