### ISSUE TITLE
DeprecationWarning: ABCs from `collections` in python3.7

### ISSUE THREAD

**Issue by iago-lito** [pandas-dev/pandas#23750]
#### Code Sample, a copy-pastable example if possible

```python
import pandas
```
#### Problem description

I receive a DeprecationWarning when testing scripts importing pandas (0.23.4) with python3.7, using `pytest` (3.9.1).

#### Expected Output

    $ py.test test.py
    ============================ test session starts =============================
    platform linux -- Python 3.7.1, pytest-3.9.1, py-1.7.0, pluggy-0.8.0
    rootdir: /home/iago-lito/tests, inifile:
    collected 0 items                                                            

    ======================== no tests ran in 0.09 seconds ========================

#### Actual Output

    $ py.test test.py
    ============================ test session starts =============================
    platform linux -- Python 3.7.1, pytest-3.9.1, py-1.7.0, pluggy-0.8.0
    rootdir: /home/iago-lito/tests, inifile:
    collected 0 items                                                            

    ============================== warnings summary ==============================
    /usr/lib/python3.7/site-packages/pandas/core/dtypes/inference.py:6: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
      from collections import Iterable

    /usr/lib/python3.7/site-packages/pandas/core/tools/datetimes.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
      from collections import MutableMapping

    -- Docs: https://docs.pytest.org/en/latest/warnings.html
    ========================= 2 warnings in 0.31 seconds =========================

#### Output of ``pd.show_versions()``

<details>

    INSTALLED VERSIONS
    ------------------
    commit: None
    python: 3.7.1.final.0
    python-bits: 64
    OS: Linux
    OS-release: 4.19.2-arch1-1-ARCH
    machine: x86_64
    processor: 
    byteorder: little
    LC_ALL: None
    LANG: fr_FR.UTF-8
    LOCALE: fr_FR.UTF-8

    pandas: 0.23.4
    pytest: 3.9.1
    pip: 18.0
    setuptools: 40.6.2
    Cython: None
    numpy: 1.15.2
    scipy: 1.1.0
    pyarrow: None
    xarray: None
    IPython: None
    sphinx: None
    patsy: None
    dateutil: 2.7.3
    pytz: 2018.7
    blosc: None
    bottleneck: None
    tables: None
    numexpr: None
    feather: None
    matplotlib: 3.0.0
    openpyxl: None
    xlrd: None
    xlwt: None
    xlsxwriter: None
    lxml: None
    bs4: None
    html5lib: 1.0.1
    sqlalchemy: None
    pymysql: None
    psycopg2: 2.7.6.1 (dt dec pq3 ext lo64)
    jinja2: 2.10
    s3fs: None
    fastparquet: None
    pandas_gbq: None
    pandas_datareader: None

</details>

**Comment by TomAugspurger** [comment]
Fixed on master. Hoping to do a release in a few weeks.

**Comment by iago-lito** [comment]
Awesome. Cheers, and keep up with the good work :)

**Comment by ntjess** [comment]
I am still seeing this error with pandas 1.0.4:

import pandas as pd

```python
def test():
  df = pd.DataFrame([[1,2,3]])
  df.to_csv('./testout.csv')
  assert True
```
in command line: `pytest ./myFile.py`

**Comment by jorisvandenbossche** [comment]
@ntjess that warning is not coming from pandas, but from a different package `s3fs`

**Comment by ntjess** [comment]
I see. I created a new environment with just `pytest` and `pandas` and indeed the error does not show.
