### ISSUE TITLE
Series: inconsistent behavior of setting value with timestamp dtype for existed index and newly-added

### ISSUE THREAD

**Issue by ianzhy** [pandas-dev/pandas#26031]
```python
sample = pd.Series([1,2],index=['a','b'])
ts = pd.Timestamp('2019-01-01')
sample['a'] = ts
sample['c'] = ts
print(sample)

```
#### output:
```
a    2019-01-01 00:00:00
b                      2
c    1546300800000000000
dtype: object
```

#### Problem description
With existed index `a`, the dtype will be Timestamp, as expected. Howerver, when setting a new index like `c`, the dtype will be int. 
Is this a bug?

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.7.final.0
python-bits: 64
OS: Darwin
OS-release: 18.2.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: zh_CN.UTF-8
LOCALE: zh_CN.UTF-8

pandas: 0.23.4
pytest: 4.0.2
pip: 18.1
setuptools: 40.6.3
Cython: 0.29.2
numpy: 1.15.4
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: 1.8.2
patsy: 0.5.1
dateutil: 2.7.5
pytz: 2018.7
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.8
feather: None
matplotlib: 3.0.2
openpyxl: 2.5.12
xlrd: 1.2.0
xlwt: 1.2.0
xlsxwriter: 1.1.2
lxml: 4.2.5
bs4: 4.6.3
html5lib: 1.0.1
sqlalchemy: 1.2.15
pymysql: 0.9.3
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: 0.7.0

</details>

**Comment by jreback** [comment]
try on 0.24.2 - irrc this is fixed

**Comment by WillAyd** [comment]
Looks like it's an issue on master. Investigation and PRs would certainly be welcome

**Comment by ianzhy** [comment]
> try on 0.24.2 - irrc this is fixed

@jreback  Just tried on 0.24.2, and it's not fixed.
By the way, what does _irrc_ mean?

**Comment by jreback** [comment]
pls try on master then

**Comment by robbuckley** [comment]
this is fixed on master, and on releases from 0.25.0. 
Output:

```
a    2019-01-01 00:00:00
b                      2
c    2019-01-01 00:00:00
dtype: object
```

so this can be closed @jreback @WillAyd

**Comment by robbuckley** [comment]
i'll take a look at adding a test for this @mroeschke

**Comment by robbuckley** [comment]
this was fixed by PR https://github.com/pandas-dev/pandas/pull/27303. This issue is really a duplicate of https://github.com/pandas-dev/pandas/issues/22717

testing added there seems enough https://github.com/pandas-dev/pandas/blob/76b8ecda9efa6b003750df19eb9d2e5b5731de55/pandas/tests/series/indexing/test_indexing.py#L734

**Comment by mroeschke** [comment]
Thanks for digging in @robbuckley! Will close.
