### ISSUE TITLE
stable docs show dirty version number

### ISSUE THREAD

**Issue by simonjayhawkins** [pandas-dev/pandas#29398]
![image](https://user-images.githubusercontent.com/13159005/68146383-c7ac1480-ff2f-11e9-9154-c0a98b13520a.png)

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.reindex.html

**Comment by WillAyd** [comment]
Yea this is related to https://github.com/pandas-dev/pandas/pull/29374#issuecomment-549080876 made a minor mistake during last release

**Comment by WillAyd** [comment]
Should be fixed now, but lmk if you see anything suspicious

**Comment by simonjayhawkins** [comment]
Thanks @WillAyd 

> lmk if you see anything suspicious

incorrect whatsnew

![image](https://user-images.githubusercontent.com/13159005/68544395-a24d5980-03ba-11ea-8975-ee7a22b895d9.png)

and google still shows version hash on search but links to correct docs

![image](https://user-images.githubusercontent.com/13159005/68544416-db85c980-03ba-11ea-98dd-531447ab8a69.png)
