### ISSUE TITLE
BUG: incompatible dtype when creating string column with loc

### ISSUE THREAD

**Issue by mortewle** [pandas-dev/pandas#55025]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame({"x": [1]})
df.loc[df["x"] == 1, "y"] = "1"
```

### Issue Description

I get a FutureWarning when conditionally creating a new string column in loc.

It does not happen if the column is numeric, assumably because float64 is the default dtype. 

The warning dissappears when setting the column to NA beforehand, but I assume this is not meant as a nessecary additional step for non-numeric columns only.

FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df["x"] == 1, "y"] = "1"

### Expected Behavior

No warning.

### Installed Versions

2.1.0

**Comment by c0mm0d0re** [comment]
how is this not a priority - so simple to fix it?

**Comment by mroeschke** [comment]
cc @MarcoGorelli

@c0mm0d0re happy to have a PR to fix this

**Comment by MarcoGorelli** [comment]
Thanks for the ping - just got back from holiday will take a look

**Comment by MarcoGorelli** [comment]
OK looks like this is due to

https://github.com/pandas-dev/pandas/blob/c74a0711f63238f9ed8ce194dbec7bcf66927f28/pandas/core/indexing.py#L1844-L1845

For now I'd suggest doing something like
```python
In [18]: ser = pd.Series(index=df.index, dtype=object)

In [19]: ser
Out[19]:
0    NaN
1    NaN
dtype: object

In [20]: ser[df['x']==1] = '1'

In [21]: ser
Out[21]:
0      1
1    NaN
dtype: object

In [22]: df['y'] = ser

In [23]: df
Out[23]:
   x    y
0  1    1
1  2  NaN
```

**Comment by MichaelTiemannOSC** [comment]
Yes.  I note that StringDtype has the na_value <NA>, but the raw string type has conflicting treatment based on scalar (np.nan) or array (string not float) context.

**Comment by OleFass** [comment]
Same thing happens when creating a column of datetime values with timezone info. When the timezone is not replaced the warning does not appear.

### Reproducible Example
```
import pandas as pd
from datetime import datetime as dt
from datetime import timezone

df = pd.DataFrame([{'id': 1},{'id': 2},{'id': 3}])
_time = dt.utcfromtimestamp(1695887042)
_time = _time.replace(tzinfo=timezone.utc)
df.loc[df.id>=2, 'time'] = _time
```
### Raised warning
```
FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '2023-09-28 07:44:10+00:00' has dtype incompatible with datetime64[ns], please explicitly cast to a compatible dtype first.
  df.loc[df.id>=2, 'time'] = _time
```

**Comment by MarcoGorelli** [comment]
this should be fixed in 2.1.2 - could you check with the latest nightly please?

you can install it with
```
pip install --pre --extra-index https://pypi.anaconda.org/scientific-python-nightly-wheels/simple pandas
```

**Comment by OleFass** [comment]
> this should be fixed in 2.1.2 - could you check with the latest nightly please?
> 
> you can install it with
> 
> ```
> pip install --pre --extra-index https://pypi.anaconda.org/scientific-python-nightly-wheels/simple pandas
> ```

This installed Version: 2.2.0.dev0+287.g824a2738dc

Unfortunately the warning still appears after running the code snippet posted earlier.

**Comment by MarcoGorelli** [comment]
thanks - could you open a new issue then please? this is a different issue then

**Comment by OleFass** [comment]
> thanks - could you open a new issue then please? this is a different issue then

[55317](https://github.com/pandas-dev/pandas/issues/55317)
Thanks for taking care of it.

**Comment by charizard-knows** [comment]
This bug still exists on 2.1.4 which is latest at the moment.

Here is a minimal reproducible example. 


```
condition = [True, False, True, True]
a = pd.DataFrame()
for i in range(len(condition)):
    df.at[i,'truth'] = condition[i]

```
Note: The issue specifically says string values whereas my example shows boolean. But since the cause is identical, it should be considered as regression and not a new issue

**Comment by MarcoGorelli** [comment]
@charizard-knows please
1. open a new issue
2. make your example reproducible (there's no `df` in your example)

**Comment by jrdunson2** [comment]
Hey -  I have a dataframe where all the columns are objects

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 15 columns):

     Column             Non-Null Count  Dtype         
 0   jobid              96 non-null     object        
 1   emailname          96 non-null     object        
 2   dataextensionname  96 non-null     object        
 3   mwemailname        96 non-null     object        
 4   subjectline        96 non-null     object        
 5   campaignids        96 non-null     object        
 6   campaignid1        96 non-null     object        
 7   campaignid2        96 non-null     object        
 8   campaignid3        96 non-null     object        
 9   campaignid4        96 non-null     object        
 10  campaignid5        96 non-null     object        
 11  department         96 non-null     object        
 12  emailtype          96 non-null     object        
 13  sentdate           96 non-null     object (see note1)
 14  src                96 non-null     object  


Note1:  this was set as a datetime but I set it back to an object per  #55317 - but this had no effect on the error below)

My version of Pandas is 2.1.4 

Note2 *** I do not have any floats64 columns

... and yet, I still get the message: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.   df.fillna('', inplace=True) #-- Removes 'NaN' values 

Note3:   I have already run the command for the dataframe: f.fillna('', inplace=True) #-- Removes 'NaN' values

- and still get the warning.   I have spent several hours just trying to get around this... and can find no help on google ... 

- Can you please help? 

Thanks
 Jarrell
