### ISSUE TITLE
DOC: pd to_datetime

### ISSUE THREAD

**Issue by PabloRuizCuevas** [pandas-dev/pandas#55239]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html

### Documentation problem

in pandas to datetime we find that the default value of the parameter exact is:

exact=_NoDefault.no_default

which i don't know what does it mean, on top of that there is inconsistent breaking behavior from last version when parsing:
 "%Y-%m-%d" if a date contains   %H:%M:%S so for me they have changed the default value from false to true in pandas v2

### Suggested fix for documentation

Probably now should be true before it was false

**Comment by Ruth-Nadel** [comment]
take

**Comment by Ruth-Nadel** [comment]
Mr. @PabloRuizCuevas , I'm on it.

**Comment by cemmanuelsr** [comment]
take

**Comment by Nrezhang** [comment]
is there a reason that exact is exact: bool | lib.NoDefault = lib.no_default, and not exact: bool = True? Should the documentation be changed to be consistent with what is written or is it ok to change it to exact: bool = True

**Comment by Aloqeely** [comment]
Thank you for this report, I believe this issue is already resolved, if you scroll down in the documentation to the parameters section, you can see it says the default value for `exact` is in fact `True`.

**Comment by lithomas1** [comment]
Yep, I think this is closable now.

The parameter should still show up as ``no_default`` in the header section i.e.
<img width="751" alt="image" src="https://github.com/pandas-dev/pandas/assets/47963215/8b84e95d-3082-45f4-9229-96678d5e9b24">

but I don't think there's a way to change that as it is autogenerated.
