### ISSUE TITLE
BUG: scipy rolling exponential is breaking MultiIndex columns

### ISSUE THREAD

**Issue by epizut** [pandas-dev/pandas#58714]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Issue Description

Adding `win_type='exponential'` to a rolling function drops the first column level.

### Reproducible Example

```python
import numpy as np
import pandas as pd

df = pd.DataFrame(
        index=pd.date_range('2024-01-01', periods=1),
        columns=pd.MultiIndex.from_product([('A', 'B'), ('a', 'b')])
    )
# the input multi-index column df
df
```
![image](https://github.com/pandas-dev/pandas/assets/1694892/4f55adee-293f-421a-bd08-41772b75339a)
```python
# the broken output with a missing first column level
df.rolling(5, min_periods=2, win_type='exponential').mean()
```
![image](https://github.com/pandas-dev/pandas/assets/1694892/95709fa8-7fbe-4c48-96a8-b66a29ca5be6)

### Expected Behavior

`.rolling(...).mean(...)` should always keep the original indexes.
![image](https://github.com/pandas-dev/pandas/assets/1694892/4f55adee-293f-421a-bd08-41772b75339a)

### Installed Versions

pandas==2.2.2
scipy==1.13.0
<details>
INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.12.3.final.0
python-bits           : 64
OS                    : Windows
OS-release            : 10
Version               : 10.0.19045
machine               : AMD64
processor             : Intel64 Family 6 Model 106 Stepping 6, GenuineIntel
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : English_United States.1252

pandas                : 2.2.2
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.9.0.post0
setuptools            : None
pip                   : 24.0
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : None
IPython               : None
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : None
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.13.0
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None
</details>

**Comment by Aloqeely** [comment]
Thanks for the report. This is fixed on the main branch

**Comment by ahawryluk** [comment]
This bug is still present in 2.2.3, and occurs for any `win_type` other than None.
