### ISSUE TITLE
RLS: 2.3

### ISSUE THREAD

**Issue by lithomas1** [pandas-dev/pandas#59664]
Release Date: ???

cc @pandas-dev/pandas-core

**Comment by mroeschke** [comment]
I updated the OP with the items to be included in 2.3. I believe the release date will be dependent on when the PDEP-14 is implemented and the pandas test suite passes with `future.infer_string`

The following PRs may need to be backported to 2.3:

* Dropping Python 3.9: https://github.com/pandas-dev/pandas/pull/58238
* Numpy 2.1 compat: https://github.com/pandas-dev/pandas/pull/59441
* Python 3.13 build wheel changes: (PRs linked from https://github.com/pandas-dev/pandas/issues/59057)

These backports probably should probably come before/after https://github.com/pandas-dev/pandas/pull/59513 cc @WillAyd

**Comment by lithomas1** [comment]
List of TODOS for infer_string (including xfailed tests) can be found here I think.

https://github.com/search?q=repo%3Apandas-dev%2Fpandas+TODO%28infer_string%29+language%3APython&type=code

**Comment by rhshadrach** [comment]
There is both a 2.3.0 and a 2.3.x branch, which one should we target for PRs?

**Comment by WillAyd** [comment]
2.3.x I made the 2.3.0 branch by mistake but can't delete it

**Comment by rhshadrach** [comment]
@jorisvandenbossche - would you have the ability to delete?

**Comment by mroeschke** [comment]
I went ahead and deleted the 2.3.0 branch

**Comment by jorisvandenbossche** [comment]
I do wonder if we should consider doing a 2.2.3 with specifically the Python 3.13 and numpy 2.1 changes. Downstream projects might appreciate that we have compatible wheels relatively soon, and when we will be exactly ready for 2.3 is still a bit unsure.

**Comment by lithomas1** [comment]
> I do wonder if we should consider doing a 2.2.3 with specifically the Python 3.13 and numpy 2.1 changes. Downstream projects might appreciate that we have compatible wheels relatively soon, and when we will be exactly ready for 2.3 is still a bit unsure.

That's a good idea.
If we follow the normal release process for 2.3.0, we'd have to do an RC aswell.
Assuming we are able to release an RC next week somehow, that would only leave 2 weeks for addressing any issues from the RC before Python 3.13 comes out, which is a pretty tight schedule.

Personally, I think it's really important that we get a Python 3.13 compatible release out before 3.13 final is due on October 1st.
https://peps.python.org/pep-0719/

Thoughts @pandas-dev/pandas-core?

**Comment by jorisvandenbossche** [comment]
I don't think next week is realistic for 2.3.0, based on the current speed of progress (I think end of the month would be my best (optimistic) estimate)

**Comment by WillAyd** [comment]
I would be OK with another 2.2.3 release if someone had time / interest for it. However, same word of caution as with 2.3 - I think getting the backport branch updated and passing tests is a rather large effort, so don't want to underestimate the time that may take

**Comment by mikev-junimo** [comment]
Has the performance regression with infer strings mentioned in https://github.com/pandas-dev/pandas/issues/59657 been fixed in 2.3.x? Because when I enable this option in 2.2 I also experience a perf regression.

**Comment by jorisvandenbossche** [comment]
@mikev-junimo good question. I took a quick look, and it seems this is not fixed on 2.3.x, only on main (thanks to https://github.com/pandas-dev/pandas/pull/57205, but that is not backported). I have opened a smaller PR to also just fix it for 2.3.x: https://github.com/pandas-dev/pandas/pull/60461

**Comment by mikev-junimo** [comment]
@jorisvandenbossche thanks! I've been wanting to enable it in our env but couldn't due to that bug.

**Comment by mroeschke** [comment]
@lithomas1 in today's dev meeting we discussed releasing 2.3 at the end of the month. Do you have bandwidth for the release?

**Comment by auderson** [comment]
@mroeschke Hi, any news on release 3.0?

**Comment by mroeschke** [comment]
> Hi, any news on release 3.0?

Ideally pandas 3.0 would come out a month or two after the 2.3 release

**Comment by lithomas1** [comment]
> [@lithomas1](https://github.com/lithomas1) in today's dev meeting we discussed releasing 2.3 at the end of the month. Do you have bandwidth for the release?

Probably not. I'm planning on stepping back from pandas/open source in about a month or so.

**Comment by MarcoGorelli** [comment]
If there's going to be a 2.3, any objections to backporting https://github.com/pandas-dev/pandas/pull/60739 ?

(https://github.com/pandas-dev/pandas/pull/60739#issuecomment-2888291202 😳 🙈 )

**Comment by lithomas1** [comment]
> Sounds good [@lithomas1](https://github.com/lithomas1). I can take care of the release.
> 
> Is https://pandas.pydata.org/docs/development/maintaining.html#release-process still up to date? Would appreciate any updates to those steps if anything has changed.

Yes I think so. It's been a while since the last release, though, so it's possible things are out of date.
Do you have access to PyPI and the pandas website?

@datapythonista should be able to add your ssh key to the pandas website.
I'm not sure who has maintainer permissions on PyPI - I can only publish releases.

**Comment by mroeschke** [comment]
I don't think there's any more blockers for 2.3 so I'll start working on the release tomorrow Wednesday June 4th.

I was able to get maintainer permissions on PyPI for pandas. I'll contact @datapythonista on a separate channel to add my ssh key to the pandas website

**Comment by a-reich** [comment]
@mroeschke will https://github.com/pandas-dev/pandas/issues/60639 be implemented in 2.3?

**Comment by mroeschke** [comment]
> will https://github.com/pandas-dev/pandas/issues/60639 be implemented in 2.3?

Yes, it will.

**Comment by mroeschke** [comment]
pandas 2.3 wheels are now available on PyPI: https://pypi.org/project/pandas/2.3.0

pandas 2.3 wheels are being generated for conda-forge: https://github.com/conda-forge/pandas-feedstock/pull/226

I will announce the release on our mailing list tomorrow; not sure if I have access to announce on our socials.

**Comment by a-reich** [comment]
FWIW the example from the release whatsnew note still raises for me on 2.3:
```
import pandas as pd, numpy as np
arr1 = pd.array([],pd.StringDtype("pyarrow", na_value=pd.NA))
arr2 = pd.array([], pd.StringDtype("python", na_value=np.nan))
arr1 == arr2 # NotImplementedError: eq not implemented for <class 'pandas.core.arrays.string_.StringArrayNumpySemantics'>
```

EDIT: created https://github.com/pandas-dev/pandas/issues/61570 to track this, although it's really a repeat of the original issue.

**Comment by mroeschke** [comment]
> FWIW the example from the release whatsnew note still raises for me on 2.3:

Could you raise an separate issue about this?

**Comment by mroeschke** [comment]
Closing this issue out as 2.3 was released

**Comment by simonjayhawkins** [comment]
Thanks @mroeschke
